openapi: 3.1.0
info:
  version: 1.0.0
  title: AquaTrack API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    This is a documentation of AquaTrack app tags
tags:
  - name: Users
    description: Users operations.
  - name: Water
    description: Operations about water.
servers:
  - url: http://localhost:3000
paths:
  /water:
    post:
      $ref: ../swagger/paths/water/create/post.yaml
  /water/{id}:
    get:
      $ref: ../swagger/paths/water/get/get.yaml
    patch:
      $ref: ../swagger/paths/water/update/patch.yaml
    delete:
      $ref: ../swagger/paths/water/delete/delete.yaml
  /water/day:
    get:
      $ref: ../swagger/paths/water/day/get.yaml
  /water/month:
    get:
      $ref: ../swagger/paths/water/month/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
